run:
  timeout: 2m
  go: "1.25"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - revive
    - misspell
    - gofumpt
    - unparam
    - unconvert
    - prealloc

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
        disabled: true
      - name: unexported-return
  gofumpt:
    extra-rules: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
